# Generated by Django 4.0.3 on 2023-02-09 11:55

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('academy', '0012_alumno_email_alter_asistencia_fecha'),
    ]

    operations = [
        migrations.CreateModel(
            name='Representante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30)),
                ('apellido', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=254, null=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_cambio', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AlterField(
            model_name='asistencia',
            name='fecha',
            field=models.DateField(default=datetime.datetime(2023, 2, 9, 7, 55, 44, 212456)),
        ),
        migrations.AddField(
            model_name='alumno',
            name='representante',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='representados', to='academy.representante'),
        ),
    ]
