# Generated by Django 4.1.5 on 2023-02-13 14:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academy', '0017_alter_asistencia_fecha_alter_pago_fecha_inicio_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asistencia',
            name='fecha',
            field=models.DateField(default=datetime.datetime(2023, 2, 13, 14, 24, 44, 759799)),
        ),
    ]
