# Generated by Django 4.0.3 on 2023-02-15 12:26

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('academy', '0019_alter_asistencia_fecha'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alumno',
            name='representante',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='representados', to='academy.representante'),
        ),
        migrations.AlterField(
            model_name='asistencia',
            name='fecha',
            field=models.DateField(default=datetime.datetime(2023, 2, 15, 8, 26, 51, 30163)),
        ),
    ]
