# Generated by Django 4.1.5 on 2023-03-02 15:05

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('academy', '0027_alter_asistencia_fecha'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='alumno',
            options={'ordering': ['nombre']},
        ),
        migrations.AlterField(
            model_name='asistencia',
            name='fecha',
            field=models.DateField(default=datetime.datetime(2023, 3, 2, 15, 5, 9, 93830)),
        ),
        migrations.CreateModel(
            name='Academia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30)),
                ('director', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='academias', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='alumno',
            name='academias',
            field=models.ManyToManyField(to='academy.academia'),
        ),
    ]
