# Generated by Django 4.1.5 on 2023-03-03 13:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academy', '0028_alter_alumno_options_alter_asistencia_fecha_academia_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='tipo_de_usuario',
            field=models.CharField(choices=[('A', 'Alumno'), ('R', 'Representante'), ('D', 'Director'), ('T', 'Tutor'), ('V', 'Visitante')], default='V', max_length=1),
        ),
        migrations.AlterField(
            model_name='asistencia',
            name='fecha',
            field=models.DateField(default=datetime.datetime(2023, 3, 3, 13, 13, 47, 370696)),
        ),
    ]
