# Generated by Django 4.1.5 on 2023-03-03 14:14

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('academy', '0030_alter_academia_director_alter_asistencia_fecha'),
    ]

    operations = [
        migrations.AddField(
            model_name='asistencia',
            name='academia',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='academias', to='academy.academia'),
        ),
        migrations.AddField(
            model_name='asistencia',
            name='tutor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tutores', to='academy.tutor'),
        ),
        migrations.AlterField(
            model_name='asistencia',
            name='fecha',
            field=models.DateField(default=datetime.datetime(2023, 3, 3, 14, 14, 39, 185263)),
        ),
    ]
