# Generated by Django 4.1.5 on 2023-03-03 18:31

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('academy', '0031_asistencia_academia_asistencia_tutor_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pago',
            name='academia',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pagos_de_una_academia', to='academy.academia'),
        ),
        migrations.AlterField(
            model_name='asistencia',
            name='fecha',
            field=models.DateField(default=datetime.datetime(2023, 3, 3, 18, 31, 58, 499937)),
        ),
    ]
