# Generated by Django 4.1.5 on 2023-03-22 17:08

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('academy', '0038_alter_asistencia_fecha'),
    ]

    operations = [
        migrations.AddField(
            model_name='representante',
            name='academia',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='representantes', to='academy.academia'),
        ),
        migrations.AlterField(
            model_name='asistencia',
            name='academia',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='asistencias', to='academy.academia'),
        ),
        migrations.AlterField(
            model_name='asistencia',
            name='fecha',
            field=models.DateField(default=datetime.datetime(2023, 3, 22, 17, 8, 51, 352053)),
        ),
        migrations.AlterField(
            model_name='asistencia',
            name='tutor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='asistencias', to='academy.tutor'),
        ),
        migrations.AlterField(
            model_name='pago',
            name='academia',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pagos_realizados', to='academy.academia'),
        ),
        migrations.AlterField(
            model_name='tutor',
            name='academia',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tutores', to='academy.academia'),
        ),
    ]
