# Generated by Django 4.1.5 on 2023-04-01 15:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academy', '0039_representante_academia_alter_asistencia_academia_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asistencia',
            name='fecha',
            field=models.DateField(default=datetime.datetime(2023, 4, 1, 15, 39, 52, 102238)),
        ),
        migrations.AlterField(
            model_name='pago',
            name='total_clases',
            field=models.DecimalField(decimal_places=1, max_digits=2),
        ),
    ]
