# Generated by Django 4.1.5 on 2023-04-01 16:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('academy', '0042_asistencia_cantidad_clases'),
    ]

    operations = [
        migrations.RenameField(
            model_name='asistencia',
            old_name='cantidad_clases',
            new_name='cantidad_sesiones',
        ),
    ]
