# Generated by Django 4.1.5 on 2023-04-05 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academy', '0043_rename_cantidad_clases_asistencia_cantidad_sesiones'),
    ]

    operations = [
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('costo_por_sesion', models.DecimalField(decimal_places=2, max_digits=3, null=True)),
                ('tipo_de_curso', models.CharField(choices=[('C', 'Continuo'), ('F', 'Fijo')], default='C', max_length=1)),
                ('cantidad_de_sesiones', models.PositiveSmallIntegerField(null=True)),
                ('costo_curso_fijo', models.DecimalField(decimal_places=2, max_digits=4, null=True)),
                ('tiempo_de_sesion', models.PositiveSmallIntegerField(null=True)),
            ],
        ),
    ]
