# Generated by Django 4.1.5 on 2023-04-07 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academy', '0046_alter_curso_costo_por_sesion'),
    ]

    operations = [
        migrations.AddField(
            model_name='representante',
            name='sexo',
            field=models.CharField(choices=[('M', 'Masculino'), ('F', 'Femenino')], max_length=1, null=True),
        ),
    ]
