# Generated by Django 4.1.5 on 2023-04-10 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academy', '0047_representante_sexo'),
    ]

    operations = [
        migrations.AddField(
            model_name='academia',
            name='url_imagen',
            field=models.URLField(null=True),
        ),
        migrations.AlterField(
            model_name='representante',
            name='sexo',
            field=models.CharField(choices=[('F', 'Femenino'), ('M', 'Masculino')], max_length=1, null=True),
        ),
    ]
