# Generated by Django 4.1.5 on 2023-04-27 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academy', '0048_academia_url_imagen_alter_representante_sexo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pago',
            name='total_clases',
            field=models.IntegerField(),
        ),
    ]
