# Generated by Django 4.1.5 on 2023-04-27 12:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('academy', '0050_alter_asistencia_cantidad_sesiones'),
    ]

    operations = [
        migrations.AddField(
            model_name='pago',
            name='curso',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pagos_realizados', to='academy.curso'),
        ),
    ]
