# Generated by Django 4.1.5 on 2023-07-13 11:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('academy', '0051_pago_curso'),
    ]

    operations = [
        migrations.AddField(
            model_name='curso',
            name='academia',
            field=models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cursos_ofertados', to='academy.academia'),
        ),
        migrations.AlterField(
            model_name='curso',
            name='tipo_de_curso',
            field=models.CharField(choices=[('C', 'Por paquete'), ('F', 'Por sesión')], default='C', max_length=1),
        ),
    ]
